"""Background concept pack vocabulary."""

from typing import Dict, List

GENERAL_DEFAULTS: Dict[str, List[str]] = {
    "lighting": [
        "soft warm lighting",
        "golden-hour light",
        "ethereal moonlit ambience",
        "colorful neon accent lights",
        "rim lighting",
        "glowing lantern light",
    ],
    "details": [
        "floating dust motes in the air",
        "handcrafted details that hint at a lived-in story",
        "light catching on delicate surfaces",
        "the interplay of light and shadow revealing depth",
        "subtle motion from drifting leaves or fabric",
    ],
    "texture": [
        "weathered wood grain",
        "polished stone floor",
        "wet cobblestone gloss",
        "smooth marble",
        "bamboo texture",
        "holographic reflections",
    ],
    "fx": [
        "soft cinematic haze",
        "volumetric light rays",
        "light leaks",
        "rain droplets on glass",
        "glowing motes of dust",
        "long exposure light trails",
    ],
    "architecture_indoor": [
        "arched doorway",
        "vaulted ceiling",
        "spiral staircase",
        "grand library shelves",
        "paper sliding doors",
    ],
    "architecture_outdoor": [
        "stone torii gate",
        "ornate wrought-iron balcony",
        "gently curving boardwalk",
        "ancient stone ruins",
        "sleek skybridge",
    ],
    "props_indoor": [
        "arranged vintage books",
        "decorative tea set",
        "stacked handwritten letters",
        "scatter of art supplies",
        "soft cushions arranged for comfort",
    ],
    "props_outdoor": [
        "lanterns lining the path",
        "flower petals on the breeze",
        "market stalls with textiles",
        "ritual offering table",
        "picnic blanket inviting rest",
    ],
}

CONCEPT_PACKS: Dict[str, Dict[str, object]] = {
    "rainy_neon_alley": {
        "label": "雨に濡れた夜の路地裏",
        "setting": "outdoor",
        "themes": ["cyberpunk_futuristic"],
        "environment": ["rain-soaked neon alley", "narrow street shimmering with reflected signs"],
        "core": ["slick reflective pavement", "towering signage overhead"],
        "lighting": ["neon signage glow", "holographic glow from billboards"],
        "weather": ["heavy rain", "wet pavement shine"],
        "time": ["midnight", "blue hour"],
        "details": ["rain cascading from awnings", "puddles mirroring electric colors"],
        "texture": ["wet asphalt gloss", "dripping chrome surfaces"],
        "props": ["flickering holographic billboard", "hanging paper lanterns"],
        "architecture": ["mega-corporation tower silhouettes", "crowded alleyway signage"],
        "fx": ["rain droplets on glass", "long exposure light trails"],
    },
    "holographic_concourse": {
        "label": "サイバーパンク都市の交差点",
        "setting": "outdoor",
        "themes": ["cyberpunk_futuristic", "space_opera"],
        "environment": ["futuristic metropolis plaza", "elevated concourse with maglev lines"],
        "core": ["streaming holographic advertisements", "dense crowd silhouettes"],
        "lighting": ["pulsing neon strips", "ambient holographic bloom"],
        "weather": ["misty air"],
        "time": ["twilight", "night"],
        "details": ["digital rain of data", "reflections in mirrored architecture"],
        "texture": ["polished alloy floor", "translucent glass panels"],
        "props": ["drifting service drones", "augmented reality kiosks"],
        "architecture": ["floating platforms", "luminescent pylons"],
        "fx": ["glitching light fragments", "lens flare from flying vehicles"],
    },
    "cozy_reading_nook": {
        "label": "木漏れ日が差す静かな読書スペース",
        "setting": "indoor",
        "themes": ["cozy_academia", "school"],
        "environment": ["sun-drenched reading nook", "bay window lined with cushions"],
        "core": ["overflowing bookshelves", "stacked handwritten notes"],
        "lighting": ["soft warm lighting", "sunlight streaming through gauzy curtains"],
        "weather": [],
        "time": ["morning light", "afternoon sun"],
        "details": ["dust motes illuminated in the air", "teacup resting beside journals"],
        "texture": ["weathered wood grain", "plush velvet seat"],
        "props": ["vintage teapot", "open sketchbook with pressed flowers"],
        "architecture": ["arched alcove", "built-in window seat"],
        "fx": ["soft vignette", "gentle haze"],
    },
    "midnight_study": {
        "label": "静寂の深夜書斎",
        "setting": "indoor",
        "themes": ["cozy_academia", "gothic_horror"],
        "environment": ["candlelit study", "antique library room"],
        "core": ["towering shelves", "glow from scattered candles"],
        "lighting": ["warm candlelight", "single reading lamp spotlight"],
        "weather": [],
        "time": ["late evening", "midnight"],
        "details": ["ink bottle and quill casting dramatic shadows", "maps pinned across the desk"],
        "texture": ["polished mahogany", "aged parchment"],
        "props": ["stack of occult tomes", "antique globe"],
        "architecture": ["vaulted ceiling", "ornate fireplace"],
        "fx": ["glowing motes of dust", "soft cinematic haze"],
    },
    "starlit_desert_bazaar": {
        "label": "星明かりの砂漠バザール",
        "setting": "outdoor",
        "themes": ["desert_oasis_arabian_nights"],
        "environment": ["moonlit desert marketplace", "lantern-lit bazaar tents"],
        "core": ["billowing textiles", "jewel-toned carpets"],
        "lighting": ["lantern glow", "starlight shimmer"],
        "weather": ["warm night breeze"],
        "time": ["night", "blue hour"],
        "details": ["incense smoke drifting", "footprints in fine sand"],
        "texture": ["woven fabrics", "polished brass"],
        "props": ["hookah set", "overflowing spice baskets"],
        "architecture": ["arched market stalls", "desert stone archways"],
        "fx": ["floating embers", "soft motion blur of dancers"],
    },
    "oasis_courtyard": {
        "label": "オアシスの静かな中庭",
        "setting": "outdoor",
        "themes": ["desert_oasis_arabian_nights", "tropical_resort"],
        "environment": ["lush oasis courtyard", "water garden surrounded by mosaic tiles"],
        "core": ["palm shadows", "cool marble benches"],
        "lighting": ["golden-hour light", "dappled sunlight through palms"],
        "weather": ["gentle breeze"],
        "time": ["sunrise", "late evening"],
        "details": ["ripples across still water", "petals floating in the pool"],
        "texture": ["glazed tile", "smooth stone"],
        "props": ["hanging lanterns", "ornate water jars"],
        "architecture": ["carved archways", "intricate lattice screens"],
        "fx": ["soft mist above the water", "sparkling light reflections"],
    },
    "enchanted_forest_clearing": {
        "label": "木漏れ日の魔法の森",
        "setting": "outdoor",
        "themes": ["fantasy", "wafu_serenity_nature"],
        "environment": ["sunlit forest clearing", "glade with luminescent flora"],
        "core": ["floating firefly lights", "ancient tree roots"],
        "lighting": ["sunlight filtering through leaves", "ethereal ambient glow"],
        "weather": ["gentle breeze"],
        "time": ["golden hour", "morning light"],
        "details": ["petals drifting in the air", "soft moss cushioning the ground"],
        "texture": ["mossy stone", "velvet foliage"],
        "props": ["stone altar overgrown with vines", "hanging charms in the branches"],
        "architecture": ["ancient stone pillars", "arch of intertwined branches"],
        "fx": ["glowing motes of dust", "magical particles floating"],
    },
    "ancient_throne_hall": {
        "label": "古の玉座の間",
        "setting": "indoor",
        "themes": ["fantasy", "space_opera"],
        "environment": ["grand throne room", "ornate ceremonial hall"],
        "core": ["draped banners", "gleaming marble floor"],
        "lighting": ["dramatic spotlight", "sunlight through stained glass"],
        "weather": [],
        "time": ["midday", "afternoon sun"],
        "details": ["floating dust caught by beams of light", "sparkling particles in the air"],
        "texture": ["polished marble", "engraved metal"],
        "props": ["ceremonial spears", "ornate throne"],
        "architecture": ["vaulted ceiling", "towering columns"],
        "fx": ["volumetric light rays", "soft haze"],
    },
    "misty_gothic_graveyard": {
        "label": "霧に包まれた墓地",
        "setting": "outdoor",
        "themes": ["gothic_horror"],
        "environment": ["misty graveyard at midnight", "ruined cemetery with leaning headstones"],
        "core": ["stone angels", "withered roses"],
        "lighting": ["moonlight breaking through fog", "cold blue rim light"],
        "weather": ["thick fog", "chilly night air"],
        "time": ["midnight"],
        "details": ["curling mist around tombstones", "faint candle offerings"],
        "texture": ["moss-covered stone", "damp earth"],
        "props": ["wrought iron gates", "flickering grave candles"],
        "architecture": ["gothic mausoleum", "crumbling chapel"],
        "fx": ["low drifting fog", "ghostly light trails"],
    },
    "candlelit_cathedral": {
        "label": "蝋燭に照らされた大聖堂",
        "setting": "indoor",
        "themes": ["gothic_horror", "cozy_academia"],
        "environment": ["gothic cathedral nave", "candlelit sanctuary"],
        "core": ["endless rows of pews", "stained glass glow"],
        "lighting": ["candles casting long shadows", "soft moonlight through stained glass"],
        "weather": [],
        "time": ["night", "late evening"],
        "details": ["smoke curling from incense", "echoes of distant choir"],
        "texture": ["stone tiles", "aged wood"],
        "props": ["candelabras", "sacred manuscripts"],
        "architecture": ["flying buttresses", "vaulted arches"],
        "fx": ["volumetric light rays", "soft vignette"],
    },
    "after_school_classroom": {
        "label": "放課後の教室",
        "setting": "indoor",
        "themes": ["school"],
        "environment": ["sunlit classroom", "orderly desks with personal touches"],
        "core": ["chalkboard notes", "scattered textbooks"],
        "lighting": ["late afternoon sun through large windows"],
        "weather": [],
        "time": ["afternoon sun", "golden hour"],
        "details": ["dust motes highlighted by sunlight", "personal doodles on the desks"],
        "texture": ["worn wooden desks", "polished linoleum"],
        "props": ["stacked notebooks", "half-erased chalkboard"],
        "architecture": ["corridor of lockers visible beyond", "traditional classroom layout"],
        "fx": ["soft vignette", "warm bloom"],
    },
    "sunset_school_rooftop": {
        "label": "夕暮れの校舎屋上",
        "setting": "outdoor",
        "themes": ["school", "cozy_academia"],
        "environment": ["school rooftop overlooking city", "railing-lined terrace"],
        "core": ["wind-swept flags", "distant skyline"],
        "lighting": ["sunset glow", "soft rim lighting"],
        "weather": ["gentle breeze"],
        "time": ["sunset", "twilight"],
        "details": ["chalk doodles on the floor", "potted plants cared for by students"],
        "texture": ["concrete tiles", "wire fencing"],
        "props": ["benches", "club equipment crates"],
        "architecture": ["fenced rooftop", "utility shed"],
        "fx": ["light leaks", "lens flare"],
    },
    "verdant_biodome_plaza": {
        "label": "緑あふれるバイオドーム広場",
        "setting": "mixed",
        "themes": ["solapunk_art_nouveau", "space_opera"],
        "environment": ["glass biodome plaza", "sunlit atrium with vertical gardens"],
        "core": ["living architecture", "solar collectors shaped like leaves"],
        "lighting": ["radiant skylight", "bioluminescent glow"],
        "weather": [],
        "time": ["daytime", "twilight"],
        "details": ["water vapor rising from hydroponic pools", "soft hum of sustainable tech"],
        "texture": ["polished glass", "lush moss"],
        "props": ["floating planters", "interactive info pillars"],
        "architecture": ["curving art nouveau arches", "transparent skybridge"],
        "fx": ["light diffraction", "glowing particles"],
    },
    "art_nouveau_conservatory": {
        "label": "アール・ヌーヴォーの温室",
        "setting": "indoor",
        "themes": ["solapunk_art_nouveau", "tropical_resort"],
        "environment": ["sunlit conservatory", "greenhouse with ornate ironwork"],
        "core": ["cascading plants", "art nouveau stained glass"],
        "lighting": ["sunbeam breaking through glass", "soft diffused glow"],
        "weather": [],
        "time": ["morning", "afternoon"],
        "details": ["mist rising from water features", "soft rustle of leaves"],
        "texture": ["glossy foliage", "ornate tile"] ,
        "props": ["hanging planters", "delicate fountains"],
        "architecture": ["arched glass ceiling", "wrought iron lattice"],
        "fx": ["soft lens flare", "floating pollen"],
    },
    "starship_bridge": {
        "label": "宇宙船ブリッジ",
        "setting": "indoor",
        "themes": ["space_opera", "cyberpunk_futuristic"],
        "environment": ["sleek starship bridge", "command center with panoramic window"],
        "core": ["holographic displays", "crew consoles"],
        "lighting": ["cool monitor glow", "strategic spotlights"],
        "weather": [],
        "time": ["deep space timelessness"],
        "details": ["floating UI projections", "captain's chair highlighted by rim light"],
        "texture": ["brushed alloy", "smooth composite panels"],
        "props": ["navigation holomap", "control panels"],
        "architecture": ["reinforced observation window", "tiered deck"],
        "fx": ["starfield reflections", "glitch sparks"],
    },
    "orbital_hangar": {
        "label": "軌道上のハンガーベイ",
        "setting": "indoor",
        "themes": ["space_opera"],
        "environment": ["massive starship hangar", "maintenance bay with docking arms"],
        "core": ["mechanical scaffolding", "cargo crates stacked high"],
        "lighting": ["industrial floodlights", "warning beacons"],
        "weather": [],
        "time": ["artificial daylight"],
        "details": ["steam vents releasing bursts", "workers silhouetted against light"],
        "texture": ["metal grating", "painted warning stripes"],
        "props": ["utility mechs", "hovering cargo pallets"],
        "architecture": ["open hangar doors", "monolithic support beams"],
        "fx": ["spark showers", "volumetric light shafts"],
    },
    "sunset_beach_boardwalk": {
        "label": "夕暮れのビーチボードウォーク",
        "setting": "outdoor",
        "themes": ["tropical_resort", "desert_oasis_arabian_nights"],
        "environment": ["sunset beach boardwalk", "palm-lined shoreline"],
        "core": ["waves lapping against shore", "string lights overhead"],
        "lighting": ["sunset glow", "warm fairy lights"],
        "weather": ["gentle sea breeze"],
        "time": ["sunset", "golden hour"],
        "details": ["footprints in wet sand", "swaying palm shadows"],
        "texture": ["weathered boardwalk", "sun-warmed sand"],
        "props": ["driftwood seating", "tropical drink stand"],
        "architecture": ["seaside cabana", "wooden pier"],
        "fx": ["light leaks", "sparkling bokeh"],
    },
    "lush_poolside_terrace": {
        "label": "リゾートのプールサイドテラス",
        "setting": "outdoor",
        "themes": ["tropical_resort", "solapunk_art_nouveau"],
        "environment": ["luxury pool terrace", "tropical garden patio"],
        "core": ["infinity pool edge", "lush foliage"],
        "lighting": ["bright daylight", "soft lantern glow after sunset"],
        "weather": ["warm breeze"],
        "time": ["daytime", "evening"],
        "details": ["sunlight sparkling on water", "condensation on chilled glasses"],
        "texture": ["smooth stone tile", "woven lounge chairs"],
        "props": ["plush lounge chairs", "floating candles"],
        "architecture": ["open-air pavilion", "curved pergola"],
        "fx": ["soft vignette", "lens flare"],
    },
    "bamboo_shrine_garden": {
        "label": "竹林の神社庭園",
        "setting": "outdoor",
        "themes": ["wafu_serenity_nature", "fantasy"],
        "environment": ["serene bamboo grove", "shrine garden with koi pond"],
        "core": ["stone lanterns", "flowing water basin"],
        "lighting": ["soft morning mist light", "paper lantern glow"],
        "weather": ["gentle drizzle", "calm breeze"],
        "time": ["morning", "dusk"],
        "details": ["ripples from koi", "petals floating on water"],
        "texture": ["smooth river stones", "mossy stepping path"],
        "props": ["wooden ema plaques", "tea set ready for ceremony"],
        "architecture": ["shinto torii gate", "wooden veranda"],
        "fx": ["light mist", "floating petals"],
    },
    "moonlit_hot_spring": {
        "label": "月明かりの温泉宿",
        "setting": "mixed",
        "themes": ["wafu_serenity_nature", "tropical_resort"],
        "environment": ["outdoor hot spring", "ryokan courtyard with steam"],
        "core": ["stone-lined onsen", "steam drifting upward"],
        "lighting": ["moonlight", "paper lantern glow"],
        "weather": ["crisp night air"],
        "time": ["night", "late evening"],
        "details": ["steam swirling gently", "bamboo ladles resting nearby"],
        "texture": ["smooth wet stone", "wooden decking"],
        "props": ["folded yukata", "sake tray"],
        "architecture": ["ryokan sliding doors", "privacy screens"],
        "fx": ["soft fog", "sparkling steam"],
    },
    "urban_twilight_street": {
        "label": "黄昏の街角",
        "setting": "outdoor",
        "themes": [],
        "environment": ["twilight city street", "quiet urban intersection"],
        "core": ["car headlights reflecting on pavement", "silhouetted pedestrians"],
        "lighting": ["streetlamp pools of light", "soft neon accents"],
        "weather": ["recent rain sparkle"],
        "time": ["twilight", "evening"],
        "details": ["shop signs flickering to life", "steam rising from manhole"],
        "texture": ["wet asphalt gloss", "brick facades"],
        "props": ["parked bicycles", "bus stop shelter"],
        "architecture": ["modern glass storefront", "historic row buildings"],
        "fx": ["light leaks", "soft haze"],
    },
    "sunlit_highland_meadow": {
        "label": "陽光の高原草原",
        "setting": "outdoor",
        "themes": [],
        "environment": ["wildflower meadow", "rolling hills under open sky"],
        "core": ["flowering grasses", "distant mountain silhouette"],
        "lighting": ["bright daylight", "sunbeam breaking through clouds"],
        "weather": ["gentle breeze"],
        "time": ["morning", "afternoon"],
        "details": ["petals drifting on the wind", "pollinator insects glinting in light"],
        "texture": ["soft grasses", "rocky outcrop"],
        "props": ["wooden fence", "picnic blanket"],
        "architecture": ["rustic cottage in the distance"],
        "fx": ["floating pollen", "cinematic haze"],
    },
}

THEME_TO_PACKS: Dict[str, List[str]] = {}
for pack_key, pack in CONCEPT_PACKS.items():
    for theme in pack.get("themes", []) or []:
        THEME_TO_PACKS.setdefault(theme, []).append(pack_key)

THEME_CHOICES: List[str] = ["none", "おまかせ"] + sorted(list(THEME_TO_PACKS.keys()))

EXCLUSIVE_TAG_GROUPS: Dict[str, List[List[str]]] = {
    "time_of_day": [
        ["sunrise", "morning", "morning light"],
        ["afternoon", "afternoon sun", "daytime", "midday"],
        ["sunset", "golden hour", "late evening", "twilight"],
        ["night", "midnight", "blue hour", "deep space timelessness"],
    ],
    "weather": [
        ["gentle breeze", "warm night breeze", "calm breeze"],
        ["heavy rain", "rain-soaked", "recent rain sparkle"],
        ["thick fog", "misty air", "soft fog"],
        ["bright daylight", "artificial daylight", "moonlight"],
    ],
}

__all__ = [
    "CONCEPT_PACKS",
    "GENERAL_DEFAULTS",
    "THEME_TO_PACKS",
    "THEME_CHOICES",
    "EXCLUSIVE_TAG_GROUPS",
]
